import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@components/Navbar";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Planner",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log("session : ", session);
  return (
    <html lang="en">
      <body>
        <Navbar session={session} />
        {children}
      </body>
    </html>
  );
}
